# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule: "every month"

# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
label_prs: update
