language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
# Setup anaconda
before_install:
  # http://conda.pydata.org/docs/travis.html
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  # - chmod +x ./cc-test-reporter
install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install -c conda-forge pytables --yes
  # - python setup.py install
  - pip install -r requirements.txt

  # Testing requirements
  - pip install pytest-flask pytest-cov python-coveralls codacy-coverage

  # Setup PyAstronomy folder
  - echo -n $HOME/PyAData > $HOME/.pyaConfigWhere
  - mkdir $HOME/PyAData

# command to run tests
script:
  # - ./cc-test-reporter before-build
  - cd sweetercat
  - pytest --cov=. --cov-report term-missing --durations 5

after_success:
  - coveralls -i
  - coverage xml -i
  - python-codacy-coverage -r coverage.xml
  # - cd ..
  # - ./cc-test-reporter after-build
