language: python
python:
  - "3.9.1"

dist: xenial
services:
  - xvfb

cache:
  directories:
    - $HOME/.cache/pip

install:
    # - python setup.py install
  - travis_retry pip install -r requirements.txt

  # Testing requirements
  - travis_retry pip install -r test_requirements.txt

  # Setup PyAstronomy folder
  - echo -n $HOME/PyAData > $HOME/.pyaConfigWhere
  - mkdir $HOME/PyAData

before_script:
  # Pre-download the PyAData.
  - cd sweetercat

script:
  - pytest --cov=. --cov-report term-missing --cov-config .coveragerc --durations 5

after_success:
  - coveralls -i
  - coverage xml -i
  - python-codacy-coverage -r coverage.xml
