language: python
python:
  - "3.5"
  - "3.6"

before_install:
    # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"  # xvfb = Virtual frame buffer
  - sleep 3                         # give xvfb some time to start

cache:
  directories:
    - $HOME/.cache/pip

install:
    # - python setup.py install
  - travis_retry pip install -r requirements.txt

  # Testing requirements
  - travis_retry pip install -r test_requirements.txt

  # Setup PyAstronomy folder
  - echo -n $HOME/PyAData > $HOME/.pyaConfigWhere
  - mkdir $HOME/PyAData

before_script:
  # Pre-download the PyAData.
  - cd sweetercat

script:
  - pytest --cov=. --cov-report term-missing --cov-config .coveragerc --durations 5

after_success:
  - coveralls -i
  - coverage xml -i
  - python-codacy-coverage -r coverage.xml
